export const data = [
    { id: 0, text: 'Организовать созвон в ДСе' },
    { id: 1, text: 'Закончить туду лист' },
    { id: 2, text: 'Написать стили' },
    { id: 3, text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation' },
    { id: 4, text: 'ullamco laboris nisi ut aliquip ex ea commodo consequat.' },
    { id: 5, text: 'Duis aute irure dolor in reprehenderit in' },
    { id: 6, text: 'voluptate velit esse cillum dolore eu fugiat nulla pariatur.' },
    { id: 7, text: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.' },
    { id: 8, text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation' },
    { id: 9, text: 'ullamco laboris nisi ut aliquip ex ea commodo consequat.' },
    { id: 10, text: 'Duis aute irure dolor in reprehenderit in' },
    { id: 11, text: 'voluptate velit esse cillum dolore eu fugiat nulla pariatur.' },
    { id: 12, text: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.' },
];